### PR TITLE
compiler: initial rebar3 support

### LINKED ISSUE #17: include_lib not found
Hi,
I'm using all the plugins to works on a project that implement a REST API with webmachine.

In my resource I have:

```erlang
-include_lib("webmachine/include/webmachine.hrl").
```

But vim say me that `can't find include lib "webmachine/include/webmachine.hrl"`.
Can someone help me? I have not an precise idea how I can fix this problem.

Thanks a lot!

### PR DESCRIPTION
**Pull request by hachreak**
* Adds a initial support for rebar3. (closes #17)

Signed-off-by: Leonardo Rossi <leonardo.rossi@studenti.unipr.it>

### CODE REVIEW

**Comment by hachreak** [comment]
ping @hcs42

**Comment by hcs42** [comment]
Thx, I will look at it soonish.

**Comment by hcs42** [comment]
The good news is that it works on my machine :)

I'd like to ask for a few changes though:

- Don't use which, grep, etc. in `os:cmd`, because those will not necessarily work on Windows.

  - You can use `os:getenv("PATH")` instead of `which`.
  - You can do the filtering in Erlang instead of "grep". That way we can also get rid of the re:replace removing `"\\e\\[0m"`, which I don't understand (`rebar3 path` on my machine only prints a single line without any formatting).
  - When you really want to execute an external command (such as when executing `rebar3 path`), you can keep using `os:cmd`.

- In [this line][proplist_line], you wrapped the result of proplists:delete into a tuple, which was not done in process_rebar_config. Is there a reason for that? I had a look at it and realized that the original code was buggy and the type specs incorrect, so fixed those in my [rebar_config branch][rebar_config]; could you look at it and let me know if you agree? (Maybe the fix will help to understand the correct behavior.)

- I'm suggesting extracting the `proplists:delete(warnings_as_errors, Opts)` expression into a function so that we don't have to duplicate the 12 lines of comments above that expression.

[proplist_line]: https://github.com/vim-erlang/vim-erlang-compiler/pull/21/commits/54c14ad719fe5215933192d4ea73e16354a567a6#diff-2cbf19b0d23ecd7a756f2e2a9e55fd94R576
[rebar_config]: https://github.com/hcs42/vim-erlang-compiler/commits/rebar_config

**Comment by billysvensson** [comment]
Great to see rebar3 support! Would it be possible for you to check for the rebar3 binary in the project root folder too?

**Comment by hachreak** [comment]
@hcs42 try to run `rebar3 path|grep ^/`
In my machine, the command doesn't return nothing because of those characters.
In my case I have also other rows:
```
===> Skipping goldrush (from {pkg,<<"goldrush">>,<<"0.1.7">>}) as an app of the same name has already been fetched
===> Skipping goldrush (from {pkg,<<"goldrush">>,<<"0.1.7">>}) as an app of the same name has already been fetched
===> Skipping goldrush (from {pkg,<<"goldrush">>,<<"0.1.7">>}) as an app of the same name has already been fetched
/my/path/_build/default/lib/webmachine/ebin
```

**Comment by hachreak** [comment]
@hcs42 If I use `os:getenv("PATH")` I retrieve a list of paths, but I can't know if the command `rebar3` is available.

**Comment by hachreak** [comment]
@hcs42 
For [the line](https://github.com/vim-erlang/vim-erlang-compiler/pull/21/commits/54c14ad719fe5215933192d4ea73e16354a567a6#diff-2cbf19b0d23ecd7a756f2e2a9e55fd94R576): 
I added there `{opt, ... }` because I needed that `load_rebar3_files()` returns it to the `load_build_files()`.
Actually, I did this change quickly without realizing that on making Copy/Paste I accidentally removed this: https://github.com/hachreak/vim-erlang-compiler/blob/rebar3_compatibility/compiler/erlang_check.erl#L426-L429.
And now you can understand why I put that code... XD

**Comment by hcs42** [comment]
> @hcs42 try to run `rebar3 path|grep ^/`
> In my machine, the command doesn't return nothing because of those characters.
> In my case I have also other rows:

Ok; I guess I didn't have those because I only created a toy project (although I did add dependencies, but probably they are not complex enough).

> @hcs42 If I use `os:getenv("PATH")` I retrieve a list of paths, but I can't know if the command `rebar3` is available.

My thought was going through the directories in "PATH" and checking if rebar3 is present in either of them.

On a second through, this may be cumbersome because on Windows `;` is used to separate directories in PATH instead of `:`. So maybe it's better to simply call "rebar3" the way we want to call it, and if it returns a non-zero value, we can try to find it in the project directory.

We made an effort in #18 to fix vim-erlang-compiler on Windows, that's why I have been trying to keep Windows support for our new rebar3 feature as well. @brainstormi, do you think you can give a hand in testing on Windows? In particular, I'm wondering if `os:cmd("QUIET=1 rebar3 path")` works on Windows just like on Unix systems.

If we can't test on Windows, then I can accept saying that our rebar3 support is Unix-only until we get someone who can help on Windows.

**Comment by hcs42** [comment]
It seems that we won't get testing on Windows, so I will test the new version of the PR on the weekend.

**Comment by hachreak** [comment]
@hcs42 I found a solution to the problem: `os:find_executable("rebar3")`! :)

**Comment by hcs42** [comment]
> @hcs42 I found a solution to the problem: `os:find_executable("rebar3")`! :)

Great finding!

I looked at the commit and made a few fixes (see the description in the commit msg):
https://github.com/hcs42/vim-erlang-compiler/commits/rebar3_compatibility

If you are happy with the fixes, we can squash the two commits together and merge the PR.

**Comment by hachreak** [comment]
ok, I cherry-picked!

**Comment by hcs42** [comment]
Thanks, merged!

**Pull request merged**
