### PR TITLE
docs: rebar3 support addition

### PR DESCRIPTION
**Pull request by hachreak**
Signed-off-by: Leonardo Rossi <leonardo.rossi@studenti.unipr.it>

### CODE REVIEW

**Comment by hcs42** [comment]
Thank you. I made a few tiny language/formatting fixes: https://github.com/hcs42/vim-erlang-compiler/commits/docs_rebar3_support → last commit. Could you check them? If you like them and squash the commit into your commit, I can merge the PR.

**Comment by hachreak** [comment]
@hcs42  Thanks for the fixes! :D

**Comment by hcs42** [comment]
> @hcs42  Thanks for the fixes! :D

I interpret this as you liking my changes :) Could you squash them into your commit?

**Comment by hachreak** [comment]
yes, sorry... I forgot to merge! XD

**Comment by hachreak** [comment]
squashed and rebased! XD
you can easily fast-forward now!

**Comment by hcs42** [comment]
Thx!

**Pull request merged**
